### ISSUE TITLE
from PersistencePython import cubePers 这里需要进行提前编译  PersistencePython.so 的吗

### ISSUE THREAD

**Issue by PhilChina** [HuXiaoling/TopoLoss#11]
您好，我想问下这里的编译的具体过程：直接使用  sh compile_pers_lib.sh 就可以了吗？ 是否还需要安装cmake、编译pybind11等操作；

还有这里的cubePers是为了计算持久图吗？我理解这里转成使用C++的代码来加速计算，我是否可以用 https://github.com/scikit-tda/persim来替代呢？

**Comment by PhilChina** [comment]
因为，我在编译的时候，提示：
pybind11-stable/include/pybind11/common.h:47:10: fatal error: Python.h: No such file or directory
 #include <Python.h>  
缺少这个文件

**Comment by HuXiaoling** [comment]
You are right that _cubePers_ is used to compute the persistence diagrams. You could use other libraries to replace _cubePers_. I would also recommend you to have a look at the more efficient version: https://github.com/HuXiaoling/TopoLoss/blob/master/topoloss_pytorch.py (use GUDHI library to compute the persistence diagrams.)

**Comment by PhilChina** [comment]
太感谢啦！
