### ISSUE TITLE
true 3D code

### ISSUE THREAD

**Issue by KaijunGao** [HuXiaoling/TopoLoss#12]
Thank you very much for your contribution,
I would like to ask when true 3D code will be released ？
Because most medical images are 3D.

**Comment by HuXiaoling** [comment]
Sorry again for late reply. As you have noticed, different from the original version, we are now using GUDHI library to reimplement the topological loss. The GUDHI based efficient 3D version is being test and we'll update here once we are done. Sorry for the inconvinience.
