### ISSUE TITLE
Boundary mask of CREMI dataset

### ISSUE THREAD

**Issue by wlsdzyzl** [HuXiaoling/TopoLoss#20]
Hello, how did you get the boundary mask of CREMI dataset? It only provides the neuron_ids. I can extract the boundareis by applying `skimage.segmentation.find_boundarys` on neuron_ids. But I got boundaries which seem thinner than what you have shown in paper. Did you add something such as a Gaussian blur? Thanks!

**Comment by HuXiaoling** [comment]
Yes, you are right that we can use the functions such as `skimage.segmentation.find_boundarys` to obtain the boundaries. Also, we use dilation/erosion operations (depending on whether the boundary is 1 or 0) to increase the thickness of the boundaries.

**Comment by wlsdzyzl** [comment]
Thanks!
