### ISSUE TITLE
About betti error

### ISSUE THREAD

**Issue by wlsdzyzl** [HuXiaoling/TopoLoss#21]
Hi, sorry to bother you again. Can you provide the details of computing BETTI error? I saw that in cldice, they computed the betti error on random 64*64 patches.  Did you do the experiments under the same setting?

**Comment by HuXiaoling** [comment]
We did the experiments under the similar setting, while the patch size is slightly different (this should be fine as long as you keep the same patch size for all the baselines). You could also choose the propriate patch size for your own dataset, and the creterion is that the patch should contain useful structures but not complex enough. Also please pay attention to the dimension of betti errors.

**Comment by wlsdzyzl** [comment]
Ok, thanks.
