### ISSUE TITLE
How to calculate β-error?

### ISSUE THREAD

**Issue by Raindow** [HuXiaoling/TopoLoss#26]
it's not very clear in you paper about how to calculate β-error? And I can't find the code in your github too.
Could you release the code?
Thank you.

**Comment by HuXiaoling** [comment]
The betti errors are simply the topological differences between corresponding patches/volumes. You can use libraries, such as GUDHI (https://gudhi.inria.fr/python/latest/cubical_complex_ref.html), to compute the betti numbers for different dimension topological structures.
