### ISSUE TITLE
A Question about the paper

### ISSUE THREAD

**Issue by qinwang-ai** [HuXiaoling/TopoLoss#5]
Hello, I just wonder that why three points wouldn't overlap together in this figure (b)'Dgm(g)', since birth and dead time of them are the same. 
![image](https://user-images.githubusercontent.com/5886719/93868570-325b6f80-fcfd-11ea-98dd-f0bda9e12dd8.png)

Many thanks,

**Comment by HuXiaoling** [comment]
Hi @wangqin4377, you are right. The three points are indeed overlapped since they have exact the same coordinates. We draw in this way just for illustration.

**Comment by qinwang-ai** [comment]
OK, thanks.
